# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.1.0
_src_path: gh:radio-aktywne/template-service-generic
accountname: radio-aktywne
description: OIDC auth 🪪
docs: true
docsurl: https://radio-aktywne.github.io/scorpion
envprefix: SCORPION
imagename: services/scorpion
registry: true
releases: true
reponame: scorpion
repourl: https://github.com/radio-aktywne/scorpion
servicename: scorpion
